import type { AstroIntegration } from 'astro';
import path from 'path';
import fs from 'fs/promises';
import YAML from 'yaml';

export interface OriCMSOptions {
  /** Site ID from OriCMS */
  siteId?: string;
  /** Path to content repository (local or git URL) */
  repo?: string;
  /** Branch to fetch (default: main) */
  branch?: string;
  /** Git token for private repos */
  token?: string;
  /** Local path to content (if not using repo) */
  contentPath?: string;
  /** Where to put content collections */
  collectionsDir?: string;
  /** Generate types from schemas */
  generateTypes?: boolean;
  /** Watch content for changes (dev mode) */
  watch?: boolean;
}

export default function oricms(options: OriCMSOptions = {}): AstroIntegration {
  const {
    siteId,
    repo,
    branch = 'main',
    token,
    contentPath = './content',
    collectionsDir = 'src/content',
    generateTypes = true,
    watch = true,
  } = options;

  return {
    name: '@oricms/astro',
    hooks: {
      'astro:config:setup': async ({ addWatchFile, config, logger, injectScript, command }) => {
        const resolvedContentPath = path.resolve(contentPath);

        // Inject Live Preview script in dev mode
        if (command === 'dev' && siteId) {
          injectScript('page', `
            import { io } from 'socket.io-client';
            
            async function initLivePreview() {
              const previewMeta = document.querySelector('meta[name="oricms-preview"]');
              if (!previewMeta) return;
              
              const [collectionId, entryId] = previewMeta.content.split(':');
              
              let token = 'preview-guest';
              try {
                const res = await fetch('http://localhost:3001/api/v1/auth/guest-token');
                const data = await res.json();
                if (data.success && data.data?.token) {
                  token = data.data.token;
                }
              } catch (e) {
                console.warn('[OriCMS] Failed to fetch guest token, using fallback', e);
              }
              
              const socket = io('http://localhost:3001', {
                path: '/presence',
                transports: ['websocket'],
                auth: { token }
              });

              socket.on('connect', () => {
                console.log('[OriCMS] Connected for Live Preview');
                socket.emit('preview:join', { siteId: '${siteId}', collectionId, entryId });
              });

              socket.on('content:preview', (data) => {
                console.log('[OriCMS] Content update received, refreshing...', data);
                window.location.reload();
              });
            }
            
            initLivePreview();
          `);
        }

        // Validate content path exists
        try {
          await fs.access(resolvedContentPath);
        } catch {
          logger.warn(`Content path not found: ${resolvedContentPath}`);
          return;
        }

        // Watch for changes in dev mode
        if (watch) {
          addWatchFile(resolvedContentPath);
        }

        // Generate types if schemas exist
        if (generateTypes) {
          try {
            await generateTypesFromSchemas(resolvedContentPath, config.srcDir);
            logger.info('Generated OriCMS types');
          } catch (error) {
            logger.warn(`Failed to generate types: ${error}`);
          }
        }
      },

      'astro:build:start': async ({ logger }) => {
        logger.info('OriCMS integration ready');
      },
    },
  };
}

async function generateTypesFromSchemas(contentPath: string, srcDir: URL): Promise<void> {
  const typesDir = path.join(srcDir.pathname, 'types');
  await fs.mkdir(typesDir, { recursive: true });

  const typeLines: string[] = [
    '// Auto-generated by @oricms/astro',
    '// Do not edit manually',
    '',
    'declare module \'oricms\' {',
  ];

  const modernSchemasDir = path.join(contentPath, 'schemas', 'types');
  const legacySchemasDir = path.join(contentPath, 'schemas', 'components');

  try {
    const modernFiles = await fs.readdir(modernSchemasDir);
    const schemaFiles = modernFiles.filter((file) => file.endsWith('.json'));

    for (const file of schemaFiles) {
      const content = await fs.readFile(path.join(modernSchemasDir, file), 'utf-8');
      const schema = JSON.parse(content) as { name?: string; label?: string; fields?: Array<{ key: string; type: string; required?: boolean }> };

      if (schema.name && Array.isArray(schema.fields)) {
        const interfaceName = toPascalCase(schema.name);
        typeLines.push(`  export interface ${interfaceName} {`);

        for (const field of schema.fields) {
          const tsType = fieldTypeToTs(field.type);
          const optional = field.required ? '' : '?';
          typeLines.push(`    ${field.key}${optional}: ${tsType};`);
        }

        typeLines.push('  }');
        typeLines.push('');
      }
    }
  } catch {
    try {
      const files = await fs.readdir(legacySchemasDir);
      const schemaFiles = files.filter(f => f.endsWith('.yaml') || f.endsWith('.yml'));

      for (const file of schemaFiles) {
        const content = await fs.readFile(path.join(legacySchemasDir, file), 'utf-8');
        const schema = YAML.parse(content);

        if (schema.name && schema.fields) {
          const interfaceName = toPascalCase(schema.name);
          typeLines.push(`  export interface ${interfaceName} {`);

          for (const field of schema.fields) {
            const tsType = fieldTypeToTs(field.type);
            const optional = field.required ? '' : '?';
            typeLines.push(`    ${field.key}${optional}: ${tsType};`);
          }

          typeLines.push('  }');
          typeLines.push('');
        }
      }
    } catch {
      // No schemas directory
    }
  }

  typeLines.push('}');

  await fs.writeFile(
    path.join(typesDir, 'oricms.d.ts'),
    typeLines.join('\n'),
    'utf-8'
  );
}

function toPascalCase(str: string): string {
  return str
    .replace(/[-_]+(.)?/g, (_, char) => (char ? char.toUpperCase() : ''))
    .replace(/^./, char => char.toUpperCase());
}

function fieldTypeToTs(type: string): string {
  const typeMap: Record<string, string> = {
    string: 'string',
    text: 'string',
    uid: 'string',
    richtext: 'string',
    'rich-text': 'string',
    markdown: 'string',
    number: 'number',
    boolean: 'boolean',
    date: 'Date | string',
    datetime: 'Date | string',
    image: '{ src: string; alt?: string; width?: number; height?: number }',
    url: 'string',
    email: 'string',
    array: 'unknown[]',
    object: 'Record<string, unknown>',
    reference: 'string',
    relation: 'string | string[]',
    asset: 'string | { src: string; alt?: string; width?: number; height?: number }',
  };
  return typeMap[type] || 'unknown';
}

// Re-export utilities
export { loadContent, type Page, type Schema } from './content.js';
