import path from 'path';
import fs from 'fs/promises';
import YAML from 'yaml';
import type { Page } from './content.js';

export interface OriCMSNextOptions {
  contentPath?: string;
  generateTypes?: boolean;
}

export interface NextCollectionOptions {
  preview?: boolean;
  limit?: number;
}

export interface NextClient {
  getCollection: <T = unknown>(collection: string, options?: NextCollectionOptions) => Promise<Array<Page & { content?: string }>>;
  getEntry: <T = unknown>(collection: string, slug: string, options?: { preview?: boolean }) => Promise<(Page & { content?: string }) | null>;
}

export function createNextClient(options: OriCMSNextOptions = {}): NextClient {
  const contentPath = options.contentPath || './content';

  return {
    async getCollection(collection, queryOptions = {}) {
      const { loadContent } = await import('./content.js');
      const entries = await loadContent({
        contentPath,
        preview: queryOptions.preview,
      });
      const filtered = entries.filter((entry) =>
        entry.metadata.collectionId === collection || entry.metadata.contentType === collection,
      );
      return typeof queryOptions.limit === 'number' ? filtered.slice(0, queryOptions.limit) : filtered;
    },
    async getEntry(collection, slug, queryOptions = {}) {
      const { loadContent } = await import('./content.js');
      const entries = await loadContent({
        contentPath,
        preview: queryOptions.preview,
      });
      return entries.find((entry) =>
        (entry.metadata.collectionId === collection || entry.metadata.contentType === collection)
        && (entry.metadata.slug === slug || entry.$id === slug)
      ) || null;
    },
  };
}

export async function generateTypesFromSchemas(contentPath: string, outputDir: string): Promise<void> {
  const typesDir = path.join(outputDir, 'types');
  await fs.mkdir(typesDir, { recursive: true });

  const typeLines: string[] = [
    '// Auto-generated by @oricms/nextjs',
    '// Do not edit manually',
    '',
    'declare module \'oricms-next\' {',
  ];

  const modernSchemasDir = path.join(contentPath, 'schemas', 'types');
  const legacySchemasDir = path.join(contentPath, 'schemas', 'components');

  try {
    const modernFiles = await fs.readdir(modernSchemasDir);
    const schemaFiles = modernFiles.filter((file) => file.endsWith('.json'));

    for (const file of schemaFiles) {
      const content = await fs.readFile(path.join(modernSchemasDir, file), 'utf-8');
      const schema = JSON.parse(content) as { name?: string; fields?: Array<{ key: string; type: string; required?: boolean }> };

      if (schema.name && Array.isArray(schema.fields)) {
        const interfaceName = toPascalCase(schema.name);
        typeLines.push(`  export interface ${interfaceName} {`);

        for (const field of schema.fields) {
          const tsType = fieldTypeToTs(field.type);
          const optional = field.required ? '' : '?';
          typeLines.push(`    ${field.key}${optional}: ${tsType};`);
        }

        typeLines.push('  }');
        typeLines.push('');
      }
    }
  } catch {
    try {
      const files = await fs.readdir(legacySchemasDir);
      const schemaFiles = files.filter((file) => file.endsWith('.yaml') || file.endsWith('.yml'));

      for (const file of schemaFiles) {
        const content = await fs.readFile(path.join(legacySchemasDir, file), 'utf-8');
        const schema = YAML.parse(content);

        if (schema.name && schema.fields) {
          const interfaceName = toPascalCase(schema.name);
          typeLines.push(`  export interface ${interfaceName} {`);

          for (const field of schema.fields) {
            const tsType = fieldTypeToTs(field.type);
            const optional = field.required ? '' : '?';
            typeLines.push(`    ${field.key}${optional}: ${tsType};`);
          }

          typeLines.push('  }');
          typeLines.push('');
        }
      }
    } catch {
      // No schema directory
    }
  }

  typeLines.push('}');

  await fs.writeFile(path.join(typesDir, 'oricms-next.d.ts'), typeLines.join('\n'), 'utf-8');
}

function toPascalCase(str: string): string {
  return str
    .replace(/[-_]+(.)?/g, (_, char) => (char ? char.toUpperCase() : ''))
    .replace(/^./, (char) => char.toUpperCase());
}

function fieldTypeToTs(type: string): string {
  const typeMap: Record<string, string> = {
    string: 'string',
    text: 'string',
    uid: 'string',
    richtext: 'string',
    'rich-text': 'string',
    markdown: 'string',
    number: 'number',
    boolean: 'boolean',
    date: 'Date | string',
    datetime: 'Date | string',
    image: '{ src: string; alt?: string; width?: number; height?: number }',
    url: 'string',
    email: 'string',
    array: 'unknown[]',
    object: 'Record<string, unknown>',
    reference: 'string',
    relation: 'string | string[]',
    asset: 'string | { src: string; alt?: string; width?: number; height?: number }',
  };
  return typeMap[type] || 'unknown';
}

export { loadContent, loadPage, loadCollectionRoot, loadSchemas, type Page, type Schema } from './content.js';
