import type { ReactNode } from 'react';
import type { CollectionConfig, CollectionEntry, ContentType, SchemaField } from '@ori/shared';
import type { useToast } from '../../contexts/ToastContext';
import type { useProject } from '../../contexts/useProject';
import type { useAuth } from '../../contexts/useAuth';
import type { useGitStatus } from '../../hooks/useGitStatus';
import type { LoadedSchemaDocument, SectionKey, SidebarOption } from '../../lib/workspace/types';
import type { CollectionBrowseController } from './collections/types';

export interface AppShellLayoutProps {
  currentProject: NonNullable<ReturnType<typeof useProject>['currentProject']>;
  projects: ReturnType<typeof useProject>['projects'];
  setCurrentProject: ReturnType<typeof useProject>['setCurrentProject'];
  isLoadingProjects: ReturnType<typeof useProject>['isLoadingProjects'];
  user: ReturnType<typeof useAuth>['user'];
  logout: ReturnType<typeof useAuth>['logout'];
  gitStatus: ReturnType<typeof useGitStatus>['status'];
  availableSections: Array<{ key: SectionKey; label: string; icon: React.ComponentType<{ width?: number | string; height?: number | string }> }>;
  activeSection: SectionKey;
  activeSectionLabel: string;
  secondaryRailCollapsed: boolean;
  setSecondaryRailCollapsed: (value: boolean) => void;
  canCreateCollections: boolean;
  activeSchemaMode: 'types' | 'components';
  componentSchemaData: LoadedSchemaDocument[];
  contentTypes: ContentType[];
  collections: CollectionConfig[];
  activeProjectSlug: string | null;
  navigateTo: (to: string, replace?: boolean) => void;
  secondaryOptions: SidebarOption[];
  activeSecondaryId: string | null;
  selectedSecondaryOption: SidebarOption | null;
  showToast: ReturnType<typeof useToast>['showToast'];
  refreshGitStatus: ReturnType<typeof useGitStatus>['refresh'];
  canCreateAssets: boolean;
  canUpdateAssets: boolean;
  canDeleteAssets: boolean;
  canManageGlobalMedia: boolean;
  currentBranchName: string;
  selectedCollection: CollectionConfig | null;
  activeEntryId: string | null;
  activeHistoryView: boolean;
  activeCollectionSettingsView: boolean;
  selectedEntry: CollectionEntry | null;
  primaryField: string;
  secondaryField: string | null;
  collectionBrowse: CollectionBrowseController;
  canCreateEntries: boolean;
  canUpdateEntries: boolean;
  canDeleteEntries: boolean;
  canUpdateCollections: boolean;
  canDeleteCollections: boolean;
  selectedEntryLoading: boolean;
  selectedEntryError: boolean;
  retrySelectedEntry: () => void;
  selectedSchemaDocument: LoadedSchemaDocument | null;
  updateCollectionsConfigPending: boolean;
  assetsQueryLoading: boolean;
  renderReadonlyFieldValue: (value: unknown, field?: SchemaField, context?: { relationLabels?: Record<string, string> }) => ReactNode;
}
