import { BaseAdapter, type ExportOptions, type TransformedPage } from '../lib/adapter.js';
import type { Schema, Page, SchemaField } from '../lib/types.js';
import path from 'path';
import fs from 'fs/promises';
import yaml from 'yaml';

const SCHEMA_VERSION = 'v1';

interface AstroAdapterConfig {
  /** Where to put content collections (relative to project root) */
  collectionsDir?: string;
  /** Where to put generated types */
  typesDir?: string;
  /** Include metadata in frontmatter */
  includeMetadata?: boolean;
  /** Format for page content: 'json' | 'yaml' | 'md' */
  format?: 'json' | 'yaml' | 'md';
}

export class AstroAdapter extends BaseAdapter {
  name = '@oricms/astro';
  version = '1.0.0';
  description = 'Export OriCMS content to Astro content collections';

  private config: Required<AstroAdapterConfig>;

  constructor(userConfig: AstroAdapterConfig = {}) {
    super();
    this.config = {
      collectionsDir: 'src/content',
      typesDir: 'src/types',
      includeMetadata: true,
      format: 'md',
      ...userConfig,
    };
  }

  async validate(options: ExportOptions): Promise<boolean> {
    await super.validate(options);

    // Check if output looks like an Astro project
    try {
      const astroConfigPath = path.join(options.outputDir, 'astro.config.mjs');
      const pkgPath = path.join(options.outputDir, 'package.json');

      await fs.access(astroConfigPath);

      const pkg = JSON.parse(await fs.readFile(pkgPath, 'utf-8'));
      if (!pkg.dependencies?.astro) {
        console.warn('Warning: Output directory may not be an Astro project');
      }
    } catch {
      console.warn('Warning: Output directory does not appear to be an Astro project');
    }

    return true;
  }

  async generateTypes(schemas: Schema[], outputPath: string): Promise<void> {
    const lines: string[] = [
      '// Auto-generated by @oricms/astro',
      '// Do not edit manually - changes will be overwritten',
      '',
      `export const SCHEMA_VERSION = '${SCHEMA_VERSION}';`,
      '',
    ];

    // Generate interfaces for each schema
    for (const schema of schemas) {
      const interfaceName = toPascalCase(schema.name);

      lines.push(`export interface ${interfaceName} {`);
      lines.push(`  /** Schema ID: ${schema.$id} */`);
      lines.push(`  $schema: '${schema.$schema}';`);

      for (const field of schema.fields) {
        const type = schemaTypeToTs(field.type, field.options);
        const optional = field.required ? '' : '?';
        const comment = field.label !== field.key ? ` // ${field.label}` : '';

        lines.push(`  ${field.key}${optional}: ${type};${comment}`);
      }

      lines.push('}');
      lines.push('');
    }

    // Generate union type for all schemas
    if (schemas.length > 0) {
      const schemaNames = schemas.map(s => toPascalCase(s.name));
      lines.push(`/** Union of all component types */`);
      lines.push(`export type AnySchema = ${schemaNames.join(' | ')};`);
      lines.push('');
    }

    // Generate page type
    lines.push(`export interface Entry<T = unknown> {`);
    lines.push(`  $id: string;`);
    lines.push(`  $schema: string;`);
    lines.push(`  $status?: 'draft' | 'published';`);
    lines.push(`  $createdAt?: string;`);
    lines.push(`  $updatedAt?: string;`);
    lines.push(`  $publishedAt?: string;`);
      lines.push(`  metadata: PageMetadata;`);
    lines.push(`  components: T[];`);
    lines.push(`  content?: string;`);
    lines.push(`}`);
    lines.push('');

    lines.push(`export interface PageMetadata {`);
    lines.push(`  title: string;`);
    lines.push(`  description?: string;`);
    lines.push(`  slug?: string;`);
    lines.push(`  publishedAt?: string;`);
    lines.push(`  [key: string]: unknown;`);
    lines.push(`}`);
    lines.push('');

    await fs.mkdir(path.dirname(outputPath), { recursive: true });
    await fs.writeFile(outputPath, lines.join('\n'), 'utf-8');
  }

  async transformPages(pages: Page[], options: ExportOptions): Promise<TransformedPage[]> {
    const transformed: TransformedPage[] = [];
    const collectionsPath = path.join(options.outputDir, this.config.collectionsDir);

    // Group entries by type/schema for collection organization
    const pagesByType = groupPagesByType(pages);

    for (const [type, typePages] of Object.entries(pagesByType)) {
      const collectionDir = path.join(collectionsPath, 'entries', type);
      await fs.mkdir(collectionDir, { recursive: true });

      for (const page of typePages) {
        const slug = page.metadata.slug || slugify(page.metadata.title);
        const fileName = `${slug}.${this.config.format}`;
        const filePath = path.join(collectionDir, fileName);

        let content: string;
        let contentType: TransformedPage['type'];

        switch (this.config.format) {
          case 'json':
            content = JSON.stringify(page, null, 2);
            contentType = 'json';
            break;
          case 'yaml':
            content = yaml.stringify(page);
            contentType = 'typescript';
            break;
          case 'md':
          default:
            content = pageToMarkdown(page);
            contentType = 'markdown';
            break;
        }

        transformed.push({
          path: filePath,
          content,
          type: contentType,
        });
      }
    }

    return transformed;
  }

  async generateConfig(options: ExportOptions): Promise<void> {
    await fs.mkdir(options.outputDir, { recursive: true });
    // Generate content.config.ts for Astro content collections
    const configPath = path.join(options.outputDir, 'content.config.ts');

    const config = `import { defineCollection, z } from 'astro:content';

// Auto-generated by @oricms/astro
export const collections = {
  entries: defineCollection({
    type: 'content',
    schema: z.object({
      $id: z.string(),
      $schema: z.string(),
      $status: z.enum(['draft', 'published']).optional(),
      $createdAt: z.string().optional(),
      $updatedAt: z.string().optional(),
      $publishedAt: z.string().optional(),
      metadata: z.object({
        title: z.string(),
        description: z.string().optional(),
        slug: z.string().optional(),
        publishedAt: z.string().datetime().optional(),
        collectionId: z.string().optional(),
        contentType: z.string().optional(),
        sourceEntryId: z.string().optional(),
      }),
      components: z.array(z.object({
        $id: z.string(),
        $type: z.string(),
        props: z.record(z.unknown()),
      })),
      content: z.string().optional(),
    }),
  }),
};
`;

    await fs.writeFile(configPath, config, 'utf-8');
  }

  async postExport(options: ExportOptions): Promise<void> {
    await fs.mkdir(options.outputDir, { recursive: true });
    // Generate README with usage instructions
    const readmePath = path.join(options.outputDir, 'GITCMS.md');

    const readme = `# OriCMS Content Collections

This directory contains content exported from OriCMS.

## Structure

\`\`\`
${this.config.collectionsDir}/
├── entries/         # Collection entries
└── ...              # Other collections
\`\`\`

## Usage

### Query entries

\`\`\`astro
---
import { getCollection } from 'astro:content';

const entries = await getCollection('entries');
---

<ul>
  {entries.map(entry => (
    <li>{entry.data.metadata.title}</li>
  ))}
</ul>
\`\`\`

### Render an entry

\`\`\`astro
---
import { getEntry } from 'astro:content';
import { render } from 'astro:content';

const entry = await getEntry('entries', 'my-entry');
const { Content } = await render(entry);
---

<article>
  <h1>{entry.data.metadata.title}</h1>
  <Content />
</article>
\`\`\`

## Regenerating

Run the export command again to refresh content:

\`\`\`bash
npx oricms export astro --source ./my-repo --out ./my-astro-site
\`\`\`

---
Generated by @oricms/cli v${this.version}
`;

    await fs.writeFile(readmePath, readme, 'utf-8');
  }
}

// Helper functions
function toPascalCase(str: string): string {
  return str
    .replace(/[^a-zA-Z0-9]+(.)/g, (_, c) => c.toUpperCase())
    .replace(/[^a-zA-Z0-9]/g, '')
    .replace(/^./, c => c.toUpperCase());
}

function schemaTypeToTs(type: string, options?: Record<string, unknown>): string {
  switch (type) {
    case 'string':
    case 'text':
    case 'uid':
    case 'richtext':
    case 'rich-text':
    case 'markdown':
    case 'image':
    case 'url':
    case 'email':
      return 'string';
    case 'number':
    case 'float':
    case 'decimal':
      return 'number';
    case 'boolean':
      return 'boolean';
    case 'date':
    case 'datetime':
      return 'Date | string';
    case 'array':
      const itemType = options?.itemType ? schemaTypeToTs(String(options.itemType)) : 'unknown';
      return `${itemType}[]`;
    case 'object':
    case 'group':
      return 'Record<string, unknown>';
    case 'reference':
    case 'relation':
      return 'string'; // Reference ID
    case 'asset':
      return '{ url: string; alt?: string; width?: number; height?: number }';
    default:
      return 'unknown';
  }
}

function groupPagesByType(pages: Page[]): Record<string, Page[]> {
  const groups: Record<string, Page[]> = {};

  for (const page of pages) {
    // Extract type from $schema or use 'pages' as default
    const schemaParts = page.$schema.split('/');
    const type = schemaParts[schemaParts.length - 1] || 'pages';

    if (!groups[type]) {
      groups[type] = [];
    }
    groups[type].push(page);
  }

  return groups;
}

function slugify(str: string): string {
  return str
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-+|-+$/g, '');
}

function pageToMarkdown(page: Page): string {
  const { metadata, components, $id, $schema, $status, $createdAt, $updatedAt, $publishedAt, content } = page;

  const frontmatter = {
    $id,
    $schema,
    $status,
    $createdAt,
    $updatedAt,
    $publishedAt,
    metadata,
    components,
  };

  return `---
${yaml.stringify(frontmatter).trim()}
---
${content || ''}
`;
}
