import { BaseAdapter, type ExportOptions, type TransformedPage } from '../lib/adapter.js';
import type { Schema, Page, SchemaField } from '../lib/types.js';
import path from 'path';
import fs from 'fs/promises';
import yaml from 'yaml';

const SCHEMA_VERSION = 'v1';

interface NextjsAdapterConfig {
    /** Where to put content collections (relative to project root) */
    collectionsDir?: string;
    /** Where to put generated types and helper functions */
    libDir?: string;
    /** Format for page content: 'json' | 'yaml' | 'md' */
    format?: 'json' | 'yaml' | 'md';
}

export class NextjsAdapter extends BaseAdapter {
    name = '@oricms/nextjs';
    version = '1.0.0';
    description = 'Export OriCMS content for Next.js (App or Pages Router)';

    private config: Required<NextjsAdapterConfig>;

    constructor(userConfig: NextjsAdapterConfig = {}) {
        super();
        this.config = {
            collectionsDir: 'content',
            libDir: 'src/lib',
            format: 'json',
            ...userConfig,
        };
    }

    async validate(options: ExportOptions): Promise<boolean> {
        await super.validate(options);

        try {
            const pkgPath = path.join(options.outputDir, 'package.json');
            const pkg = JSON.parse(await fs.readFile(pkgPath, 'utf-8'));
            if (!pkg.dependencies?.next) {
                console.warn('Warning: Output directory may not be a Next.js project');
            }
        } catch {
            console.warn('Warning: Output directory does not appear to be a Next.js project');
        }

        return true;
    }

    async generateTypes(schemas: Schema[], outputPath: string): Promise<void> {
        const lines: string[] = [
            '// Auto-generated by @oricms/nextjs',
            '// Do not edit manually - changes will be overwritten',
            '',
            `export const SCHEMA_VERSION = '${SCHEMA_VERSION}';`,
            '',
        ];

        for (const schema of schemas) {
            const interfaceName = toPascalCase(schema.name);

            lines.push(`export interface ${interfaceName} {`);
            lines.push(`  /** Schema ID: ${schema.$id} */`);
            lines.push(`  $schema: '${schema.$schema}';`);

            for (const field of schema.fields) {
                const type = schemaTypeToTs(field.type, field.options);
                const optional = field.required ? '' : '?';
                const comment = field.label !== field.key ? ` // ${field.label}` : '';

                lines.push(`  ${field.key}${optional}: ${type};${comment}`);
            }

            lines.push('}');
            lines.push('');
        }

        if (schemas.length > 0) {
            const schemaNames = schemas.map(s => toPascalCase(s.name));
            lines.push(`/** Union of all component types */`);
            lines.push(`export type AnySchema = ${schemaNames.join(' | ')};`);
            lines.push('');
        }

        lines.push(`export interface Entry<T = unknown> {`);
        lines.push(`  $id: string;`);
        lines.push(`  $schema: string;`);
        lines.push(`  $status?: 'draft' | 'published';`);
        lines.push(`  $createdAt?: string;`);
        lines.push(`  $updatedAt?: string;`);
        lines.push(`  $publishedAt?: string;`);
        lines.push(`  metadata: PageMetadata;`);
        lines.push(`  components: T[];`);
        lines.push(`  content?: string;`);
        lines.push(`}`);
        lines.push('');

        lines.push(`export interface PageMetadata {`);
        lines.push(`  title: string;`);
        lines.push(`  description?: string;`);
        lines.push(`  slug?: string;`);
        lines.push(`  publishedAt?: string;`);
        lines.push(`  collectionId?: string;`);
        lines.push(`  contentType?: string;`);
        lines.push(`  sourceEntryId?: string;`);
        lines.push(`  [key: string]: unknown;`);
        lines.push(`}`);
        lines.push('');

        await fs.mkdir(path.dirname(outputPath), { recursive: true });
        await fs.writeFile(outputPath, lines.join('\n'), 'utf-8');
    }

    async transformPages(pages: Page[], options: ExportOptions): Promise<TransformedPage[]> {
        const transformed: TransformedPage[] = [];
        const collectionsPath = path.join(options.outputDir, this.config.collectionsDir);

        const pagesByType = groupPagesByType(pages);

        for (const [type, typePages] of Object.entries(pagesByType)) {
            const collectionDir = path.join(collectionsPath, 'entries', type);
            await fs.mkdir(collectionDir, { recursive: true });

            for (const page of typePages) {
                const slug = page.metadata.slug || slugify(page.metadata.title);
                const fileName = `${slug}.${this.config.format}`;
                const filePath = path.join(collectionDir, fileName);

                let content: string;
                let contentType: TransformedPage['type'];

                switch (this.config.format) {
                    case 'md':
                        content = pageToMarkdown(page);
                        contentType = 'markdown';
                        break;
                    case 'yaml':
                        content = yaml.stringify(page);
                        contentType = 'typescript';
                        break;
                    case 'json':
                    default:
                        content = JSON.stringify(page, null, 2);
                        contentType = 'json';
                        break;
                }

                transformed.push({
                    path: filePath,
                    content,
                    type: contentType,
                });
            }
        }

        return transformed;
    }

    async generateConfig(options: ExportOptions): Promise<void> {
        const isAppRouter = await fs.access(path.join(options.outputDir, 'app')).then(() => true).catch(() => false);
        const libPath = path.join(options.outputDir, isAppRouter ? 'src/lib' : 'lib');
        await fs.mkdir(libPath, { recursive: true });

        const helperPath = path.join(libPath, 'oricms.ts');

        const helper = `// Auto-generated by @oricms/nextjs
import fs from 'fs/promises';
import path from 'path';
import type { Entry } from './types/oricms';

const CONTENT_DIR = path.join(process.cwd(), '${this.config.collectionsDir}', 'entries');

export async function getCollection<T>(collection: string, options: { preview?: boolean } = {}): Promise<Entry<T>[]> {
  try {
    const dirPath = path.join(CONTENT_DIR, collection);
    const files = await fs.readdir(dirPath);
    
    const entries = await Promise.all(
      files
        .filter(f => f.endsWith('.json'))
        .map(async (file) => {
          const content = await fs.readFile(path.join(dirPath, file), 'utf-8');
          return JSON.parse(content) as Entry<T>;
        })
    );
    
    return options.preview ? entries : entries.filter((entry) => entry.$status !== 'draft');
  } catch (error) {
    console.warn(\`Failed to read collection \${collection}:\`, error);
    return [];
  }
}

export async function getEntry<T>(collection: string, slug: string, options: { preview?: boolean } = {}): Promise<Entry<T> | null> {
  try {
    const filePath = path.join(CONTENT_DIR, collection, \`\${slug}.json\`);
    const content = await fs.readFile(filePath, 'utf-8');
    const entry = JSON.parse(content) as Entry<T>;
    if (!options.preview && entry.$status === 'draft') {
      return null;
    }
    return entry;
  } catch (error) {
    return null;
  }
}
`;

        await fs.writeFile(helperPath, helper, 'utf-8');
    }

    async postExport(options: ExportOptions): Promise<void> {
        await fs.mkdir(options.outputDir, { recursive: true });
        const readmePath = path.join(options.outputDir, 'GITCMS.md');

        const readme = `# OriCMS Content
This directory contains content exported from OriCMS.

## Structure
\`\`\`
${this.config.collectionsDir}/
├── entries/         # Collection entries
└── ...              # Other collections
\`\`\`

## Next.js Usage (App Router)

### Fetch all entries
\`\`\`tsx
import { getCollection } from '@/lib/oricms';

export default async function PageList() {
  const posts = await getCollection('blog-post');
  return (
    <ul>
      {posts.map(p => <li key={p.$id}>{p.metadata.title}</li>)}
    </ul>
  );
}
\`\`\`

### Fetch single entry
\`\`\`tsx
import { getEntry } from '@/lib/oricms';

export default async function SinglePage({ params }: { params: { slug: string } }) {
  const page = await getEntry('blog-post', params.slug);
  if (!page) return <h1>Not found</h1>;
  return <h1>{page.metadata.title}</h1>;
}
\`\`\`

---
Generated by @oricms/cli v${this.version}
`;

        await fs.writeFile(readmePath, readme, 'utf-8');
    }
}

// Helpers
function toPascalCase(str: string): string {
    return str
        .replace(/[^a-zA-Z0-9]+(.)/g, (_, c) => c.toUpperCase())
        .replace(/[^a-zA-Z0-9]/g, '')
        .replace(/^./, c => c.toUpperCase());
}

function schemaTypeToTs(type: string, options?: Record<string, unknown>): string {
    switch (type) {
        case 'string': case 'text': case 'uid': case 'richtext': case 'rich-text': case 'markdown': case 'image': case 'url': case 'email':
            return 'string';
        case 'number': case 'float': case 'decimal':
            return 'number';
        case 'boolean':
            return 'boolean';
        case 'date': case 'datetime':
            return 'Date | string';
        case 'array':
            return options?.itemType ? `${schemaTypeToTs(String(options.itemType))}[]` : 'unknown[]';
        case 'object': case 'group':
            return 'Record<string, unknown>';
        case 'reference': case 'relation':
            return 'string';
        case 'asset':
            return '{ url: string; alt?: string; width?: number; height?: number }';
        default:
            return 'unknown';
    }
}

function groupPagesByType(pages: Page[]): Record<string, Page[]> {
    const groups: Record<string, Page[]> = {};
    for (const page of pages) {
        const type = page.metadata.contentType || page.metadata.collectionId || page.$schema.split('/').filter(Boolean).pop() || 'entries';
        if (!groups[type]) groups[type] = [];
        groups[type].push(page);
    }
    return groups;
}

function slugify(str: string): string {
    return str.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-+|-+$/g, '');
}

function pageToMarkdown(page: Page): string {
    return `---
${yaml.stringify({
  $id: page.$id,
  $schema: page.$schema,
  $status: page.$status,
  $createdAt: page.$createdAt,
  $updatedAt: page.$updatedAt,
  $publishedAt: page.$publishedAt,
  metadata: page.metadata,
  components: page.components,
}).trim()}
---
${page.content || ''}
`;
}
